#!/usr/bin/env python
import sys
from pkg_resources import load_entry_point


def patch_babel():
    # Hack babel to support Language header
    import babel.messages.catalog

    _get_mime_headers = babel.messages.catalog.Catalog._get_mime_headers

    def _get_mime_headers_with_language(self):
        headers = _get_mime_headers(self)
        if self.locale is not None:
            headers.append(('Language', str(self.locale)))
        return headers

    babel.messages.catalog.Catalog.mime_headers = property(_get_mime_headers_with_language, babel.messages.catalog.Catalog._set_mime_headers)


if __name__ == '__main__':
    patch_babel()
    sys.exit(
        load_entry_point('Babel', 'console_scripts', 'pybabel')()
    )
