//
//  CUTENotificationKey.h
//  currant
//
//  Created by Foster Yin on 4/22/15.
//  Copyright (c) 2015 Foster Yin. All rights reserved.
//

#ifndef currant_CUTENotificationKey_h
#define currant_CUTENotificationKey_h

#define KNOTIF_USER_DID_LOGIN @"KNOTIF_USER_DID_LOGIN"

#define KNOTIF_USER_WILL_LOGOUT @"KNOTIF_USER_WILL_LOGOUT"

#define KNOTIF_USER_DID_LOGOUT @"KNOTIF_USER_DID_LOGOUT"

#define KNOTIF_USER_DID_UPDATE @"KNOTIF_USER_DID_UPDATE"

#define KNOTIF_USER_VERIFY_PHONE @"KNOTIF_USER_VERIFY_PHONE"

#define KNOTIF_MARK_USER_AS_LANDLORD @"KNOTIF_MARK_USER_AS_LANDLORD"

#define KNOTIF_TICKET_PUBLISH @"KNOTIF_TICKET_PUBLISH"

#define KNOTIF_TICKET_WECHAT_SHARE @"KNOTIF_TICKET_WECHAT_SHARE"

#define KNOTIF_TICKET_LIST_RELOAD @"KNOTIF_TICKET_LIST_RELOAD"

#define KNOTIF_PROPERTY_SHARE @"KNOTIF_PROPERTY_SHARE"

#define KNOTIF_HIDE_ROOT_TAB_BAR @"KNOTIF_HIDE_ROOT_TAB_BAR"

#define KNOTIF_SHOW_ROOT_TAB_BAR @"KNOTIF_SHOW_ROOT_TAB_BAR"

#define KNOTIF_SHOW_HOME_TAB @"KNOTIF_SHOW_HOME_TAB"

#define KNOTIF_SHOW_SPLASH_VIEW @"KNOTIF_SHOW_SPLASH_VIEW"

#endif
