//
//  CUTENotificationKey.h
//  currant
//
//  Created by Foster Yin on 4/22/15.
//  Copyright (c) 2015 Foster Yin. All rights reserved.
//

#ifndef currant_CUTENotificationKey_h
#define currant_CUTENotificationKey_h

#define KNOTIF_USER_DID_LOGIN @"KNOTIF_USER_DID_LOGIN"

#define KNOTIF_USER_DID_LOGOUT @"KNOTIF_USER_DID_LOGOUT"

#define KNOTIF_BETA_USER_DID_REGISTER @"KNOTIF_BETA_USER_DID_REGISTER"

#define KNOTIF_TICKET_PUBLISH @"KNOTIF_TICKET_PUBLISH"

#define KNOTIF_TICKET_EDIT @"KNOTIF_TICKET_EDIT"

#define KNOTIF_TICKET_CREATE @"KNOTIF_TICKET_CREATE"

#define KNOTIF_TICKET_WECHAT_SHARE @"KNOTIF_TICKET_WECHAT_SHARE"

#define KNOTIF_TICKET_LIST_RELOAD @"KNOTIF_TICKET_LIST_RELOAD"

#define KNOTIF_HIDE_ROOT_TAB_BAR @"KNOTIF_HIDE_ROOT_TAB_BAR"

#define KNOTIF_SHOW_ROOT_TAB_BAR @"KNOTIF_SHOW_ROOT_TAB_BAR"

#define KNOTIF_SHOW_FAVORITE_RENT_TICKET_LIST @"KNOTIF_SHOW_FAVORITE_RENT_TICKET_LIST"

#define KNOTIF_SHOW_FAVORITE_PROPERTY_LIST @"KNOTIF_SHOW_FAVORITE_PROPERTY_LIST"

#define KNOTIF_SHOW_RENT_TICKET_LIST_TAB @"KNOTIF_SHOW_RENT_TICKET_LIST_TAB"

#define KNOTIF_SHOW_PROPERTY_LIST_TAB @"KNOTIF_SHOW_PROPERTY_LIST_TAB"

#define KNOTIF_SHOW_SPLASH_VIEW @"KNOTIF_SHOW_SPLASH_VIEW"

#endif
