source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

#xcodeproj 'currant'

link_with 'currant', 'currant-dev', 'currant-test', 'currant-production', 'currantTests'

pod 'BBTUtility', :git => "git@git.bbtechgroup.com:bbt/ios-bbtutility.git"
pod 'BBTRestClient', :git => "git@git.bbtechgroup.com:bbt/ios-bbtrestclient.git"
pod 'AFNetworkActivityLogger', '~> 2.0.4'
pod 'FXForms', '~> 1.2.12'
pod 'SMCalloutView', '~> 2.1.1'
pod 'ngrvalidator', '~> 1.0.0'
pod 'INTULocationManager', '~> 3.0.1'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'WebViewJavascriptBridge', '~> 4.1.4'
pod 'Bolts', '~> 1.1.4'
pod 'Sequencer', '~> 1.0.1'
pod 'CTAssetsPickerController', '~> 2.9.3'
pod 'Masonry', '~> 0.6.1'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'UIActionSheet+Blocks', '0.8.1'
pod 'UIAlertView+Blocks', '0.8.1'
pod 'MWPhotoBrowser', '~> 1.4.1'
pod 'YTKKeyValueStore'
pod 'TTTAttributedLabel', '~> 1.13.3'
pod 'RegExCategories', '~> 1.0'
pod 'NSDate-Extensions'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.11'
pod 'apptentive-ios', '~> 1.7.3'
pod 'JDFTooltips'
pod 'UMengSocial', '~> 4.2.3'
pod 'WeiboSDK', :podspec => 'https://raw.github.com/sinaweibosdk/weibo_ios_sdk/master/WeiboSDK.podspec'
pod 'ALActionBlocks', '~> 1.0.3'
pod 'Aspects', '~> 1.4.1'
