source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

#xcodeproj 'currant'

link_with 'currant', 'currant-dev', 'currant-test', 'currant-production', 'currantTests'

pod 'BBTUtility', :git => "git@git.bbtechgroup.com:bbt/ios-bbtutility.git"
pod 'BBTRestClient', :git => "git@git.bbtechgroup.com:bbt/ios-bbtrestclient.git"
pod 'SMCalloutView', '~> 2.1.1'
pod 'FXModelValidation', '~> 1.0.4'
pod 'INTULocationManager', '~> 3.0.1'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'Bolts', '~> 1.1.4'
pod 'Sequencer', '~> 1.0.1'
pod 'CTAssetsPickerController', '~> 2.9.3'
pod 'Masonry', '~> 0.6.1'
pod 'SVProgressHUD', '~> 1.1.3'
