source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

#xcodeproj 'currant'

link_with 'currant', 'currant-dev', 'currant-test', 'currant-production', 'currantTests'

pod 'BBTUtility', :git => "git@git.bbtechgroup.com:bbt/ios-bbtutility.git"
pod 'BBTRestClient', :git => "git@git.bbtechgroup.com:bbt/ios-bbtrestclient.git"
pod 'AFNetworkActivityLogger', '~> 2.0.4'
pod 'SMCalloutView', '~> 2.1.1'
pod 'ngrvalidator', '~> 1.0.0'
pod 'INTULocationManager', '~> 3.0.1'
pod 'NJKWebViewProgress', '~> 0.2.3'
pod 'Bolts', '~> 1.1.4'
pod 'Sequencer', '~> 1.0.1'
pod 'CTAssetsPickerController', '~> 2.9.3'
pod 'Masonry', '~> 0.6.1'
pod 'SVProgressHUD', '~> 1.1.3'
pod 'UIActionSheet+Blocks', '0.8.1'
pod 'UIAlertView+Blocks', '0.8.1'
pod 'MWPhotoBrowser', '~> 1.4.1'
pod 'libWeChatSDK', :git => "https://github.com/Fykec/libWeChatSDK.git"
pod 'YTKKeyValueStore'
pod 'KVOController'
pod 'TTTAttributedLabel', '~> 1.13.3'
pod 'JRSwizzle', '~> 1.0'

pod 'FLEX', '~> 2.0', :configurations => ['Debug']
